plugins {
    `maven-publish`
}

allprojects {
    version="4.0.0-SNAPSHOT"
    group="me.tippie"
}

tasks.create("release") {
    dependsOn(":tippieutils-1_21_R1:build")
    // Get the release jars from the projects (tippieutils-1_21_R1)

    doLast {
        val shadowJar = project(":tippieutils-1_21_R1").tasks.getByName("shadowJar")
        val shadowJarOutputs = shadowJar.outputs.files.files
        val destinationDir = rootProject.layout.buildDirectory.get().asFile.resolve("libs")
        destinationDir.mkdirs()

        // Print the files generated by shadowJar
        shadowJarOutputs.forEach {
            shadowJarOutputs.forEach { jarFile ->
                val releaseJarFile = file("${destinationDir}/tippieutils-${version}-1_21_R1.jar")
                jarFile.copyTo(releaseJarFile, overwrite = true)
            }
        }
    }
}

publishing {
    publications.create<MavenPublication>("mavenJava") {
        groupId = project.group.toString()
        artifactId = project.name.lowercase()
        version = project.version.toString()
        // Specify the custom JAR with the new classifier
        val artifactDir = rootProject.layout.buildDirectory.get().asFile.resolve("libs")
        artifact(artifactDir.resolve("tippieutils-$version-1_21_R1.jar")) {
            classifier = "1_21_R1"
        }
    }

    repositories {
        maven {
            credentials {
                username = findProperty("tippieRepoUsername") as String?
                password = findProperty("tippieRepoPassword") as String?
            }
            url = if(project.version.toString().endsWith("-SNAPSHOT")) {
                uri("https://repo.tippie.me/repository/maven-public-snapshots/")
            } else {
                uri("https://repo.tippie.me/repository/maven-public-releases/")
            }
        }
    }
}