import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.7"
    id("io.papermc.paperweight.userdev") version "1.7.2"
}

paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION

dependencies {
    paperweight.paperDevBundle("1.21.1-R0.1-SNAPSHOT")
    implementation(project(":tippieutils-core"))
}

tasks {
    jar.configure {
        archiveClassifier = "slim"
    }
    shadowJar.configure {
        archiveClassifier = null
    }

    build {
        dependsOn("shadowJar")
    }

}

java {
    withSourcesJar()
    withJavadocJar()
}