# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with maven

on: [push, pull_request]

jobs:
  wild_1_19:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache 1.19 Maven package
        id: cacheWild
        uses: actions/cache@v2
        with:
            path: |
              ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/
              ~/.m2/repository/org/spigotmc/spigot-parent/
              ~/.m2/repository/org/spigotmc/minecraft-server/
            key: ${{ runner.os }}-spigot-1.19-all
            restore-keys: ${{ runner.os }}-spigot-1.19-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.19
          restore-keys: ${{ runner.os }}-m2_1.19

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.19 Spigot
        id: wild
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/spigot-1.19-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19 Spigot (Mojang)
        id: wildMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/spigot-1.19-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19 Spigot (Obf)
        id: wildObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/spigot-1.19-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.19
        if: steps.wild.outputs.sucess != 'true' || steps.wildMojang.outputs.sucess != 'true' || steps.wildObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.19 --remapped
  build:
    runs-on: ubuntu-latest
    needs: [wild_1_19]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Cache 1.19 Maven package
      id: cacheWild
      uses: actions/cache@v2
      with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.19-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.19-all
          restore-keys: ${{ runner.os }}-spigot-1.19-all
    - uses: s4u/maven-settings-action@v2.3.0
      with:
          servers: |
            [{
                "id": "tippie-repo",
                "username": "${{ secrets.TIPPIE_REPO_USERNAME }}",
                "password": "${{ secrets.TIPPIE_REPO_PASSWORD }}"
            }]
    - name: Build with Maven
      run: mvn -B package javadoc:jar source:jar org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:aggregate --file pom.xml
